```{r}
library(stringr)
library(plotrix)
library(dplyr) #doubleplayer
```

# 데이터 정제하기

```{r}
election <- read.csv("./Data/election_2022.csv")




# key 값은 시군구 + 광역시도
#election$지명 = paste(election$광역시도,election$시군구)
election$electionSum = apply(election[,5:7],1,sum)
#election$electionPercent = election$투표수 * 100 /election$선거인수
election$electionRatio = election$electionSum * 100 /election$투표수

election
```

electionRatio가 가장 높은 지역과 낮은 지역

-   arrange 이용해서 하기

```{r}
arrange(election,electionRatio)[1,c(8,11)]
arrange(election,desc (electionRatio))[1,c(8,11)]
```

-   subset 이용해서 하기

```{r}
subset(election,select = c(8,11),
       election$electionRatio == max(election$electionRatio))
subset(election,select = c(8,11),
       election$electionRatio == min(election$electionRatio))
```

csv로 저장하기

```{r}
write.csv(election,"./Data/election_2022_job.csv", row.names = F)
```

election ratio 의 평균

```{r}
election$electionRation_sd <-(election$electionRatio - mean(election$electionRatio))**2
election

election$electionRatio_변동계수 = election$electionRation_sd / election$electionRatio

arrange(election, desc (electionRatio))[1,c(8,11)]
arrange(election,  (electionRatio_변동계수))

election
```

# 1번.광역시별 투표율을 3D Pie Chart로 표현하기

-   벡터로 시행착오 겪은거

```{r}
length(unique(election$광역시도))
par(family = "AppleGothic")
col
votePer <- matrix(rep(0,17),1,17)
votePer
a<-aggregate(투표수~광역시도,election,sum)

votePer <- arrange(a,desc (a$투표수))[,2]

arrange(a,desc (a$투표수))[,2]

length(votePer)

length(arrange(a,desc (a$투표수))[,1])
c<-arrange(a,desc (a$투표수))[,1]
c
names(votePer) <- c

pie3D(votePer,
      main = "광역시도별 투표율",
      labels = paste(names(votePer),"\n",round(votePer/sum(votePer)*100,2),"%"),
      labelcex = 0.5
      )
```

-   깔끔하게 정리하기

```{r}
par(family = "AppleGothic")

aggregate(투표수~광역시도,election,sum)
elec_sum_order <-arrange(aggregate(투표수~광역시도,election,sum),desc (투표수))

round(sum(elec_sum_order[c(1,2,5),2])/sum(elec_sum_order[,2]) * 100,2)

pie3D(arrange(aggregate(투표수~광역시도,election,sum),desc (투표수))[,2],
      main ="광역시도별 투표율",
      labels = paste(arrange(aggregate(투표수~광역시도,election,sum),desc (투표수))[,1],
                     "\n",
                     round(arrange(aggregate(투표수~광역시도,election,sum),desc (투표수))[,2]/
                      sum(election$투표수)*100,2),"%"),
      labelcex = 0.5,
      explode =  0.05
      )
```

-   쓸데없는 컬럼 지우기

```{r}
25.23 + 19.26 + 6.36
```

# 2번. 윤석열 후보의 광역시도별 득표율

```{r}
par(family = "AppleGothic")

aggregate(윤석열~광역시도,election,sum)
yoon_sum_order<-arrange(aggregate(윤석열~광역시도,election,sum),desc (윤석열))

yoon_per_reg<-arrange(aggregate(윤석열~광역시도,election,sum),desc (윤석열))[,2] /
sum(election$윤석열)*100

yoon_per_reg <-ifelse(round(yoon_per_reg,1) < 3,"",paste(round(yoon_per_reg,1),"%"))

pie3D(yoon_sum_order[,2],
      labels = paste(yoon_sum_order[,1],"\n",yoon_per_reg),
      labelcex = 0.8
      )
```

# 윤석열 후보의 서울득표 Top5만 득표율로 표시하고 나머지 지역은 기타로 합치기

```{r}
par(family = "AppleGothic")

election[,c(1,2,6)]

# 서울특별시에서 윤석열 투표수만 뽑아오기
#seoul_yoon <- subset(election,select = c(1,2,6), 광역시도 == "서울특별시")
seoul_yoon <- election[election$광역시도 == '서울특별시', ]

# 서울특별시 내림차순 정렬
seoul_yoon_order <- arrange(seoul_yoon, desc (윤석열))

# seoul_yoon_sum vector 만들어서 5위 까지와 기타로 나눔
seoul_yoon_sum<-c(seoul_yoon_order[1:5,3],sum(seoul_yoon_order[-(1:5),3]))

# label에 쓰기 위해서 names 해주는 거
names(seoul_yoon_sum) <- c(head(seoul_yoon_order,5)[,2],"기타")

# label에 들어갈 percentage 넣기
seoul_yoon_per <- round(seoul_yoon_sum / sum(seoul_yoon_sum) * 100,2)

# draw pie chart 
pie3D(seoul_yoon_sum,
      main = "윤석열 후보 서울 득표 Top5",
      labels = paste(names(seoul_yoon_sum),"\n",seoul_yoon_per,"%"),
      labelcex = 0.8,
      explode = 0.1
      )
```

# 3번.후보별 출생지 득표율

```{r}
election
```

-   윤석열 후보 : 성북구

```{r}
vote_sung<-election[election$광역시도 == '서울특별시' & election$시군구 == '성북구',4:7]
```

```{r}
par(family="AppleGothic")
vote_sung[,2:4]
vote_sung[,1] - sum(vote_sung[,2:4])

# 타입이 다를 때
vote_sung_vec<-as.numeric(c(vote_sung[,2:4],vote_sung[,1] - sum(vote_sung[,2:4])))
names(vote_sung_vec)<-c(colnames(vote_sung[,2:4]),"기타")
vote_sung_vec<-round(vote_sung_vec / vote_sung[,1] * 100,2)
vote_sung_vec

pie3D(vote_sung_vec,
      labels = paste(names(vote_sung_vec),"\n",vote_sung_vec,"%"),
      labelcex = 0.7
      )
```

# 4번. 투표수가 가장많은 4지역(광역시도) 막대그래프로 만들기

```{r}
par(family="AppleGothic")

top4<-arrange(aggregate(cbind(투표수,이재명,윤석열,심상정)~광역시도,election,sum),-(투표수))[1:4,]

top4_mat<-t(as.matrix(top4[,3:5]))
colnames(top4_mat)<-top4[,1]

# 지수를 일반숫자로 표시
options(scipen = 100)

barplot(top4_mat,
        ylim = c(0,5*10**6),
        col = c("skyblue","red","yellow"),
        beside =T,
        legend.text = T,
        main = "투표수가 가장 많은 4지역의 후보별 득표수 차이",
        cex.axis = 0.5
)


```

aggregate 이용하지 않고 해보기

```{r}
par(family="AppleGothic")

# start 
aggregate(투표수~광역시도,election,sum)
top4_reg<-arrange(aggregate(투표수~광역시도,election,sum),-(투표수))[1:4,]
top4_reg

top4_reg_election<-subset(election,광역시도 =="경기도" |광역시도 =="서울특별시" | 광역시도 =="부산광역시" | 광역시도 =="경상남도")
top4_reg_election

# 이재명
top4_lee<-aggregate(이재명~광역시도,top4_reg_election,sum)
# 윤석열
top4_yoon<-aggregate(윤석열~광역시도,top4_reg_election,sum)
# 심상정
top4_sim<-aggregate(심상정~광역시도,top4_reg_election,sum)

# top4_lee , top4_yoon , top4_sim 과 top4_reg 의 순서가 달라서 오류가 생긴다. 
# 이걸 순서에 맞게 어떻게 넣어줄까
# merge 해주면 된다. 이 븅아
top4_reg <- merge(x = top4_reg ,y= top4_lee, by.x = "광역시도",by.y = "광역시도")
top4_reg <- merge(x = top4_reg ,y= top4_yoon, by.x = "광역시도",by.y = "광역시도")
top4_reg <- merge(x = top4_reg ,y= top4_sim, by.x = "광역시도",by.y = "광역시도")
# end 
# 이 과정이 
# arrange(aggregate(cbind(투표수,이재명,윤석열,심상정)~광역시도,election,sum),-(투표수))
# 과 같다

top4_met2<-t(as.matrix(arrange(top4_reg,-(투표수))[,3:5]))

colnames(top4_met2)<-top4_reg$광역시도

barplot(top4_met2,
        ylim = c(0,5*10**6),
        col = c("skyblue","red","yellow"),
        beside =T,
        legend.text = T,
        main = "투표수가 가장 많은 4지역의 후보별 득표수 차이",
        cex.axis = 0.5
)

```

# 5번. 투표수가 높은 시군구의 후보별 투표수

```{r}
par(family="AppleGothic")

vote_top5_reg<-arrange(election,desc (투표수))[1:5,1:2]
vote_top5_reg$region = paste(vote_top5_reg$광역시도,vote_top5_reg$시군구)

vote_top5_num3<-arrange(election,desc (투표수))[1:5,5:7]
vote_top5_mat<-t(vote_top5_num3)

colnames(vote_top5_mat) <-vote_top5_reg$region

options(scipen = 100)

barplot(vote_top5_mat,
        ylim = c(0,6*10**5),
        col = c("skyblue","red","yellow"),
        legend.text = T,
        main = "투표수가 높은 지역의 후보별 투표수",
        cex.axis = 0.5,
        cex.names = 0.7,
        space = 0.3
        )
```
