# 혼자 해보기

```{r}
titanic.train <- read.csv("./Data/Titanic_train.csv")
titanic.train
```

```{r}
titanic.train$Survived <- factor(titanic.train$Survived, 
												levels = c(0,1) , 
												labels = c("death","alived")
												)

titanic.train$Sex <- as.factor(titanic.train$Sex)
```

```{r}
library(dplyr)
titanic.train<-arrange(titanic.train , Survived)
titanic.train
```

# Age 처리 - NA 빼기

# Age 처리 - pclass에 따라 median

-   age NA인 애들의 pclass 보기

```{r}
table(ifelse( is.na(titanic.train$Age) , titanic.train$Pclass , 0))
```

```{r}
# pclass 별 age 평균값 보기
first_class <- subset(titanic.train[,c(2,3,6)], Pclass == 1)
second_class <- subset(titanic.train[,c(2,3,6)], Pclass == 2)
third_class <- subset(titanic.train[,c(2,3,6)], Pclass == 3)
```

```{r}
# median : 37
summary(first_class)
# median : 29
summary(second_class)
# median : 24
summary(third_class)
```

```{r}
library(stringr)
first_class$Age  <- str_replace_na(first_class$Age , 37.00)
second_class$Age <- str_replace_na(second_class$Age , 29.00)
third_class$Age  <-  str_replace_na(third_class$Age , 24.00)
```

```{r}
age <- c(first_class$Age , second_class$Age , third_class$Age)
```

```{r}
titanic.train<-arrange(titanic.train, Pclass)
titanic.train$Age <- age
titanic.train <- arrange(titanic.train, Survived)
```

-   class 도 상관이 있는 것 같다.

```{r}
table(first_class$Survived)
table(second_class$Survived)
table(third_class$Survived)
```

## 연령도 feature로 들어갈 수 있을까?

-   연령 범위 보기

```{r}
titanic.train$Age <- as.numeric(titanic.train$Age)
range(titanic.train$Age)
```

```{r}
age_category <- c(0,1,5,13,seq(20,80,10))
```

-   나이 범위 별 산사람과 죽은사람 비율

```{r}
death<-subset(titanic.train, Survived == "death")
alived<-subset(titanic.train, Survived == "alived")

table(cut(death$Age, breaks = age_category,right = F))
table(cut(alived$Age, breaks = age_category,right = F))
```

-   있는 것 같다.

```{r}
table(titanic.train$Survived,titanic.train$SibSp)
table(titanic.train$Survived,titanic.train$Parch)
table(titanic.train$Survived,titanic.train$Embarked)

unique(titanic.train$Embarked)
```

# RandomForest model 만들기

```{r}
titanic.train_T <- titanic.train
```

```{r}
titanic.train_T$Sexcode[titanic.train_T$Sex == "male"] <- 0
titanic.train_T$Sexcode[titanic.train_T$Sex == "female"] <- 1
```

```{r}
titanic.train_T$Embarked_C = titanic.train_T$Embarked == "C"
titanic.train_T$Embarked_S = titanic.train_T$Embarked == "S"
titanic.train_T$Embarked_Q = titanic.train_T$Embarked == "Q"
```

```{r}
# 2,3,6,10,13,14,15,16
```

```{r}
titanic.train_T <- titanic.train_T[,c(2,3,6,10,13,14,15,16)]
```

```{r}
samp <- createDataPartition(titanic.train_T$Survived, p = 0.7 , list = F)
data.train <- titanic.train_T[samp,]
data.test <- titanic.train_T[-samp,]
```

```{r}
x <- subset(data.test , select = -Survived)
y <- data.test$Survived
```

```{r}
titanic.rf <- randomForest(Survived ~ . ,data.train , ntree = 100)
pred <- predict(titanic.rf , x)
```

```{r}
mean(pred == y) * 100
# 죽은 사람은 잘 맞추는데 , 산 사람은 반 밖에 못맞춘다. 
table(pred, y)
```

```{r}

```
