# for 문

```{r}
c <- vector()

for (i in 1:10) {
  c<-append(c,i)
}
c
```

1 - 100까지의 홀수만 출력하기

```{r}
c <- vector()

for(i in seq(1,100,2)){
  c <- append(c,i)
}

c
```

제곱근

```{r}
# cat 과 print가 비슷한 거
# paste는 그냥 문자열 붙여주는거 ,sep 로 사이사이 모 들어갈지 해주는거
# print 쓰고 문자열 쓰면 "" 들어감

for(i in 1:10){
    cat(paste(i,"=>",sqrt(i)),"\n")
}
```

1부터 100까지의 짝수의 합계 구하기

```{r}
data <- 1:100

sum <- 0

# for 문 쓰는 방법
for (a in data) {
  if (a %% 2 == 0) {
    sum <- sum(sum , a)
  }
  
}

cat(paste('1부터 100까지의 짝수의 합은 ',sum, ' 입니다.',"\n",sep = ""))

# ifelse 사용하는 방법
sum(ifelse(data %% 2 == 0,  data , 0))
```

```{r}
excel <- read.csv("./Data/excel.csv")

data <- excel$q3
data
sumEven <- sumOdd <- 0

for (i in data) {
  if(i %%2 == 0){
    sumEven <- sumEven + i
  }else{
    sumOdd <- sumOdd + i
  }
}

sum(ifelse(data%%2 == 0, data, 0 ))
sumEven
sumOdd
```

```{r}
for(i in 1:9){
  cat(i," * 2 = ", i *2 , "\n")
}
```

# Function

-   funcion의 집합이 library가 되는것이다.

```{r}
gugu2 <- function(a){
  for(i in 1:9){
  cat(i," * ", a , " = ", i * a , "\n")
}
}

gugu2(4)
```

```{r}
gugu3 <- function(a,b){
  for(i in 1:b){
  cat(a," * ", i , " = ", i * a , "\n")
}
}

gugu3(2,12)
```

```{r}
for(a in vector1){
  for(b in vector2){
    cat(a," * ", b , " = ", a * b , "\n")
  }
  cat("--------------------------", "\n")
}
```

```{r}
gugu4 <- function(vector1,vector2){
  for(a in vector1){
    for(b in vector2){
      cat(a," * ", b , " = ", a * b , "\n")
    }
    cat("--------------------------", "\n")
  }
}


a <- c(1,2,3,4)
b <- c(2,3,4,5)

gugu4(a,b)
```

```{r}
score <- c(85,95,89)
name <- c("유비","관우","장비")

cat(paste(name,":",score,"\n"),sep="")
```

# While

```{r}
i <- 0
while( i < 10){
  i = i + 1
  print(i)
}

i<-0

while(T){
  i = i+ 1
  print(i)
  if(i > 9){
    break
  }
}
```

# Repeat

-   while(T)와 같은 의미라고 생각하면 된다.

```{r}
i <- 0
repeat{
  i = i + 1
  if(i > 10){
    break
  }
  print(i)
}
```

# 함수

함수는 코드의 집합이다.

-   내장 함수

```{r}
vec<-10:20
min(vec)
max(vec)
mean(vec)
median(vec)

```

```{r}
gugu5 <- function(vector1,vector2){
  for(a in vector1){
    for(b in vector2){
      cat(a," * ", b , " = ", a * b , "\n")
    }
  }
}
  
gugu5(2:3,1:5)
```

# 결측치(na) 자료 평균 계산

-   not available 이다.

```{r}
data<-c(10,20,5,4,40,7,NA,6,3,NA,2,NA)
```

```{r}
is.na(data)
sum(is.na(data))
table(is.na(data))
```

1.  na를 빼고 평균값 구하기

```{r}
mean(data, na.rm = T)
```

-   이 밑에 방법중 마음에 드는 방법을 선택하는 것이 분석에서 중요하다.

-   na = 0

```{r}
#case 1
# NA <- 0 으로 해서 평균을 구하기
library(stringr)

# na replace 하는 방법 1
data2<-str_replace_na(data,0)
data2<-as.numeric(data2)
mean(data2)

# na replace 하는 방법 2 
mean(ifelse(is.na(data),0,data))
```

-   na = mean

```{r}
#case 2
# NA <- mean 으로 해서 평균을 구하기
# 이 방법은 데이터를 뭉개버리는 것이지 의미가 없다.
mean(ifelse(is.na(data),mean(data,na.rm = T),data))

```

-   na = median

```{r}
# case 3
# NA <- median
mean(ifelse(is.na(data),median(data,na.rm = T),data)
```

-   na = max

```{r}
# case 4
# NA <- max
mean(ifelse(is.na(data),max(data,na.rm = T),data))
```

-   na = min

```{r}
# case 5
# NA <- min
mean(ifelse(is.na(data),min(data,na.rm = T),data))
```

-   na가 40% 이상인 데이터는 가치가 없다.
