# 시뮬레이션

#### 왜 하는가?

-   내가 데이터가 없을 때 이를 증명하기 위해서 필요하다.

-   예를 들어 내가 만약 동전을 던져서 앞 뒤가 나올 확률이 50% 라는 것을 증명하고 싶다고 하자. 이를 증명할 데이터가 없다면 우리는 시뮬레이션을 통해 이를 증명해야 된다.

## 몬테카를로 시뮬레이션

### 동전의 앞면 뒷면 시뮬레이션

```{r}
# 이 방법은 시뮬레이션 결과가 쌓이지 않는다. 그래서 함수를 만들기로 했다. 
x <- runif(1,0,1)
if(x < 1/2){
  # 앞면이라 생각하자.
  result = 0
}else{
  # 뒷면이라 생각하자.
  result = 1 
}
print(result)
```

```{r}
coin <- function(a){
  result <- vector()
  for (i in 1:a) {
    x <- runif(1,0,1)
    
    if(x < 1/2){
        # 앞면이라 생각하자. 0 
        result <- append(result,0)
      }else{
        # 뒷면이라 생각하자. 1
        result <- append(result,1)
      }
  }
  cat(result)
}
```

```{r}
table(coin(100))
mean(coin(100))
```

### 가위 바위 보 시뮬레이션

```{r}
# 가위 바위 보를 했을 때 이길 확률이 1/3 이 맞는지 확인해보기
# 0 초과  1 이하
# 1 초과  2 이하
# 2 초과  3 이하
person1 <- ceiling(runif(1,0,3))
person1
person2 <- ceiling(runif(1,0,3))
person2

# 1  가위
# 2  바위
# 3  보

# 이길 경우
if((person1 > person2 & person1 - person2 == 1) | (person1 == 1 & person2 == 3)){
  result = "이김"
}else if(person1 == person2){
  result = "비김"
}else {
  result = "졌음"
}


print(result)
```

```{r}
rock <- function(a){
  countWin = 0;
  countSame = 0;
  countLose = 0;
  for (i in 1:a) {

    person1 <- ceiling(runif(1,0,3))
    person1
    person2 <- ceiling(runif(1,0,3))
    person2
    
    if((person1 > person2 & person1 - person2 == 1) | (person1 == 1 & person2 == 3)){
      countWin = countWin + 1
    }else if(person1 == person2){
      countSame = countSame + 1
    }else {
      countLose = countLose + 1
    }
    
  }
  
  cat("이김 : ", countWin, "\n")
  cat("비김 : ", countSame, "\n")
  cat("졌음 : ", countLose, "\n")
  cat("-----------------------------","\n")
}
```

```{r}
rock(10)
rock(100)
rock(1000)
rock(10000)
rock(100000)

```

```{r}
#  person1 <- ceiling(runif(1,0,3)) 이렇게 해도 되는지 궁금
scissor <- function(a){
  vec <- vector()
  
  for(i in 1:a){
    person1 <- trunc(runif(1)*3) + 1
    vec <- append(vec,person1)
  }
  vec
}
```

```{r}
hi <-table(scissor(10000))
names(hi) <- c("rock","scissor","paper")
hi
```

## 주사위 시뮬레이션

-   선생님이 알려주신 거

```{r}
dice <- function(a){
  diceFace <- rep(0,6)
  cat("Throw : ", a,"\n")
  for (i in 1:a) {
    num <- trunc(runif(1)*6) + 1
    diceFace[num] = diceFace[num] + 1
  }
  
  cat("No 1 => ", diceFace[1],"\n")
  cat("No 2 => ", diceFace[2],"\n")
  cat("No 3 => ", diceFace[3],"\n")
  cat("No 4 => ", diceFace[4],"\n")
  cat("No 5 => ", diceFace[5],"\n")
  cat("No 6 => ", diceFace[6],"\n")
  cat("----------------","\n")
}
```

-   내 맘대로 한 거

```{r}
dice2 <- function(a){
  vec <- vector()
  
  for(i in 1:a){
    num <- trunc(runif(1)*6) + 1
    vec <- append(vec,num)
  }
  vec
}
```

-   simulation 결과

```{r}
dice(1000)
table(dice2(1000))
length(dice2(1000))
```
