# 데이터 시각화 2

# \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## 선굵기 변경하기

```{r}
x <- c(1,3,5,2,9,10)
plot(x,
     type = "b",
     col = c(rep("darkgray",5),"red"),
     lwd = 3
     )
```

## 한 화면에 차트 여러개 그려서 비교하기

```{r}
price <- runif(10,1,100)
plot(price)
```

```{r}
par(mfrow = c(2,2))

plot(price,
     type = "l"
     )

plot(price,
     type = "o"
     )

plot(price,
     type = "h"
     )

plot(price,
     type = "s"
     )
```

## pch 속성으로 그리기

```{r}
par(mfrow = c(4,5))

for (i in 1:20) {
  plot(price,
       type = "o",
       pch = i
       )
}
```

```{r}
plot(price,
     type = "o",
     pch = c(rep(20,8),15,15)
     )
```

## 중첩 자료 시각화

### Method1

```{r}
x <- c(1,2,3,4,2,4)
y <- rep(2,6)

plot(y ~ x)
```

```{r}
table(x,y)
```

```{r}
xy.df <- as.data.frame(table(x,y))
xy.df
plot(y ~ x,
     pch = 15,
     cex = xy.df$Freq
     )
```

### Method2

```{r}
x <- c(1,1,1,2,2,2,2,2,2,3,3,4,5,6,2)
y <- c(1,1,4,2,3,2,2,3,2,1,1,1,2,3,2)
zz <- data.frame(x,y)
sunflowerplot(zz)
zz
```

```{r}
# sunflowerplot 으로 iris의 Sepal.Length 와 Sepal.Width의 산포도 그리기
sunflowerplot(iris$Sepal.Length ~ iris$Sepal.Width)
```

## 차트 겹쳐서 출력하기

```{r}
x <- 1:10
y <- 10:1
mycol <- rgb(0,0,1,seq(0,1,0.1))

dotchart(x,
         col = "red"
         )

par(new = T)

barplot(x,
        col = mycol
        )

par(new = T)

barplot(y,
        col = rgb(1,0,0,c(1,0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1))
        )
```

## 상자 수염 그래프

-   이상한 데이터 (이상치) 확인 하는 그래프

```{r}
abc <- c(110, 300, 150, 280, 310)

# 상자 수염 그래프
# 이를 통해 오른쪽으로 치우쳐진 skew postive 한 그래프라는 것을 알아야 한다. 
boxplot(abc,
        col = "yellow",
        horizontal = T
        )

# 정규분포를 따를 때의 최소값이 맨 왼쪽 선
# 1사분면 값이 박스 맨 왼쪽 선
# 중앙값은 진한 검정 선
# 3사분면 값은 박스 맨 오른쪽 선
# 정규분포를 따를 때의 최대값이 맨 오른쪽 선 
```

```{r}
summary(abc)
```

```{r}
def <- c(1,1,1,1,1,2,5)
summary(def)
```

```{r}
# 이상치는 점으로 나타나게 된다.
# 결측치 + 이상치가 40%가 넘었을 경우는 분석 데이터로 사용하기에는 적합하지 않다고 판단해도 좋다. 
boxplot(def)
```

### 예제

[1] 자동차의 제동거리

```{r}
head(cars)
str(cars)
plot(cars$dist ~ cars$speed)
```

```{r}
hist(cars$dist)
```

```{r}
summary(cars$dist)
```

```{r}
boxplot(cars$dist,
        horizontal = T
        )

boxplot(cars$speed,
        horizontal = T
        )
```

## 차트 디자인

```{r}
par(family = "AppleGothic")

x<-c(1,3,6,8,9)
y<-c(12,56,78,32,9)


plot(y ~ x,
     ann = F,
     axes = F
     )
# (3,3) 과 (4,4) 를 연결하는 선분(segment) 그리기
segments(8,32,6,78,col = "red")

# 화살표 그리기
arrows(3,56,1,12,col = "blue")

# 글자쓰기
text(4,40,
     "This is sparta",
     srt = 180 # 회전 시킴 각도로 표기
     )

# 테두리 활용하기
mtext("Character", 
      side = 4, # 밑(6시방향)에서 부터 시계방향으로 1,2,3,4 이다. 
      adj = 1 # side에 위치할 위치 0이 side 기준 왼쪽 ,0.5가 center, 1이 side 기준 오른쪽 
      )

# 테두리 그리기
box(lty = 1,
    col = "red"
    )

# 사각형 그리기
rect(4,20,6,30,
     density = 30,
     col = "red"
     )

# x축 추가 , y축 40 위치에 0~10 까지 표시하고 색은 빨간색
axis(1,
     pos = 40,
     at = 0:10,
     col = "red"
     )

# y축 추가 , x축의 6 위치에 20 - 60 까지 표시하기 색은 파란색
axis(2,
     pos = 6,
     at = 20:60,
     col = "blue"
     )
```

### 예제

[1] 투표수가 높은 시군구 top 5 의 후보별 득표수의 막대그래프에 시군구별 투표수 표시하기

```{r}
library(stringr)
library(dplyr)
```

```{r}
election <- read.csv("./Data/election_2022.csv")
election
election_top5<-arrange(election,desc (투표수))[1:5,5:7]
election_top5_dist <- arrange(election,desc (투표수))[1:5,1:2]
election_top5_vote<- arrange(election,desc (투표수))[1:5,4]

election_top5_mat<-cbind(t(election_top5[1,]),t(election_top5[2,]),t(election_top5[3,]),t(election_top5[4,]),t(election_top5[5,]))
colnames(election_top5_mat)<-paste(election_top5_dist$광역시도,election_top5_dist$시군구)
```

```{r}
par(family = "AppleGothic")

barplot(election_top5_mat,
        col = c("skyblue","red","yellow"),
        ylim = c(0,6*10^5),
        cex.names = 0.7,
        cex.axis = 0.7,
        las = 1,
        main = "투표수 높은 지역의 후보별 투표 수"
        )

options(scipen = 100)

# 글자쓰기
text(seq(0.7,0.7 + (length(election_top5_vote)-1) * 1.2 ,1.2),apply(election_top5, 1, sum)+2*10^4,
     election_top5_vote,
     cex = 0.7
     )

legend(5,6*10^5,
       c("심상정","윤석열","이재명"),
       fill = c("yellow","red","skyblue"),
       cex = 0.9
       )
```

```{r}
election_top5_mat
percent_vec<-vector()
x_place<-vector()
y_place<-vector()

for (y in 1:ncol(election_top5_mat)) {
  for (x in 1:nrow(election_top5_mat)) {
      # 넣을 숫자 
      percent<-round(election_top5_mat[x,y] * 100 /sum(election_top5_mat[,y]),2)
      percent_vec <- append(percent_vec,percent)
      
      #x좌표
      x_place <- append(x_place, 0.7 + (y-1) * 1.2)
      
      #y좌표
      temp <- x
      temp_y <- 0
      while (temp > 1) {
        temp <- temp - 1
        temp_y <- temp_y + election_top5_mat[temp,y]
      }
      
      y_place <- append(y_place,temp_y + election_top5_mat[x,y] / 2)
     
  }
}


```

```{r}
par(family = "AppleGothic")

barplot(election_top5_mat,
        col = c("skyblue","red","yellow"),
        ylim = c(0,6*10^5),
        cex.names = 0.7,
        cex.axis = 0.7,
        las = 1,
        main = "투표수 높은 지역의 후보별 투표 수"
        )

options(scipen = 100)

# 글자쓰기
text(x_place,y_place,
     paste(percent_vec,"%",sep = ""),
     cex = ifelse(percent_vec >= 3,0.7,0.4)
     )

legend(5,6*10^5,
       c("심상정","윤석열","이재명"),
       fill = c("yellow","red","skyblue"),
       cex = 0.9
       )
```

## qplot()을 이용한 산점도

```{r}
library(ggplot2)
```

```{r}
qplot(Sepal.Length , Petal.Length , 
      data = iris, 
      col = Species,
      size = Petal.Width
      )
```

# 수학 함수의 시각화

```{r}
f <- function(x){
  y = x^2
  return(y)
}
```

```{r}
x<- 1:3 
f(x)
```

```{r}
x<- seq(-10,10,0.1)
plot(f(x)~x,
     type = "l"
     )

```

```{r}
g <- function(x){
  y = x^2 + 2*x + 3
  return(y)
}

(x+1)^2 + 2
```

```{r}
x <- seq(-6,4,0.1)

plot(g(x)~x,
     type = "l",
     ylim = c(0,max(g(x)))
     )
```
