```{r}
library(stringr)
library(dplyr)
library(plotrix)
```

# 주제 1. 세종시는 과연 서울의 인구 밀도를 줄여줬을까?

## 우리나라 인구수의 특징에 대해서 일단 알아보자.

```{r}
pop_reg

ex3<-aggregate(인구수~년도,pop_reg,sum)
ex3
par(family = "AppleGothic")

(ex3[2,2]-ex3[1,2])/ex3[1,2]*100

ex4<-vector()

for(i in 2:nrow(ex3)){
  ex4<-append(ex4,(ex3[i,2]-ex3[i-1,2])/ex3[i-1,2]*100)
}

round(ex4,2)

ex4<-data.frame(ex3[-1,1],round(ex4,2))
tail(ex4)
colnames(ex4)<-c("년도","증감 비율")
ex4

plot(ex4$`증감 비율` ~ ex4$년도,
     ylim = c(-0.5,1.5),
     type = "l"
     )


1 + ex4[,2]/100 
a<-1
for (i in 1:28) {
  a<- a * (1 + ex4[i,2]/100 )
}

a <- a^(1/28)
a
```

## 기하평균 이용해서 인구 증감 비율의 평균 알아보기

```{r}
tail(ex4)
a<-ex4[1,2]
# 기하평균 구하기
for (i in 2:nrow(ex4)) {
  a<-ex4[i,2] * a
}

a <- a^(1/28)
a
```

지역의 면적과 인구수가 관련이 있는가?

없다 라고 볼 수 있다.

```{r}
cor(pop_density_reg$인구수,pop_density_reg$면적)
```

## 광역시도별 인구수 평균 그래프

```{r}
par(family = "AppleGothic")


pop_reg_group<-arrange(aggregate(인구수~광역시도,pop_reg,mean),desc (인구수))
label<-paste(pop_reg_group$광역시도,"\n",round(pop_reg_group$인구수/sum(pop_reg_group$인구수)*100,2),"%")

pie3D(pop_reg_group$인구수,
      labels = label,
      labelcex = 0.8
      )
```

## 수도권 인구수와 지방 인구수 비교(년도별)

수도권의 면적이 지방에 비해 헌저히 작지만 인구수를 비교해보면 알 수 있다. 왜 상관이 없는지

```{r}
ex1<- subset(pop_reg,광역시도 == "서울특별시" |
         광역시도 == "인천광역시" |
         광역시도 == "경기도" )

pop_sudokwon<-aggregate(인구수~년도,ex1,sum)

ex1<-subset(pop_reg,!(광역시도 == "서울특별시" |
         광역시도 == "인천광역시" |
         광역시도 == "경기도" ))

pop_be_sudokwon<-aggregate(인구수~년도,ex1,sum)

pop_be_sudokwon
pop_sudokwon

tail(pop_sudokwon)

pop_sudokwon$인구수 > pop_be_sudokwon$인구수
```

```{r}
par(family="AppleGothic")

options(scipen = 100)

plot(pop_be_sudokwon,
     ylim =c(1.9*10^7,2.8*10^7),
     cex.axis = 0.5,
     type = "l",
     col = "red",
     lty= 1,
     main = "년도별 수도권 비수도권 인구수"
     )

lines(pop_sudokwon,
      type = "l",
      col = "blue",
      lty= 1
      )

legend(2015, 2.3*10^7,
      c("지방","수도권"),
			 cex = 0.8 ,
       col = c("red","blue"),
       lty = c(1,1)
       )
```

## 2006 \~ 2020 년 까지 각 지역별 인구 밀도 평균을 비교해보자.

```{r}
pop_density_reg
```

```{r}
par(family = "AppleGothic")

pop_density_dist<-arrange(aggregate(인구밀도~광역시도,pop_density_reg,mean),desc (인구밀도))

barplot(pop_density_dist$인구밀도,
        names = pop_density_dist$광역시도,
        ylim = c(0,20000),
        cex.names = 0.4,
        col = ifelse(pop_density_dist$광역시도 == "서울특별시"|
                      pop_density_dist$광역시도 == "인천광역시"|
                      pop_density_dist$광역시도 == "경기도","red","blue"),
        main = "광역시도별 평균 인구밀도",
        xlab = "광역시도" , 
        ylab = "인구밀도(km2 당 인구 수)"
        )
```

## 서울 특별시의 인구밀도가 월등히 높다는 것을 알 수 있다.

## 광역시도별 인구밀도가 어떻게 변화했는지 알아보도록 하자.

```{r}
ex2<-subset(pop_density_reg, 광역시도 == "서울특별시")
ex2
```

```{r}
par(family = "AppleGothic")

for (reg in unique(pop_density_reg$광역시도)) {
  ex1<-subset(pop_density_reg, 광역시도 == reg)
  plot(ex1$인구밀도~ex1$년도,
       ylim = c(min(ex1$인구밀도)-100,max(ex1$인구밀도)+100),
       type = "b",
       xlab = "년도",
       ylab = "인구밀도( km2당 인구 수 )",
       pch = 1,
       col = "blue",
       main = paste(reg,"연도별 인구 밀도",sep = " ")
       )
}
```

## 지역별 변동계수도 구해보자

```{r}
pop_reg.mean<-aggregate(인구수~광역시도,pop_reg,mean)
pop_reg.mean
pop_reg.sd<-aggregate(인구수~광역시도,pop_reg,sd)
pop_reg.sd

pop_reg.cv <- pop_reg.sd$인구수 / pop_reg.mean$인구수

pop_reg_cv <- data.frame(광역시도 = pop_reg.mean$광역시도,변동계수 = pop_reg.cv)
pop_reg_cv <- arrange(pop_reg_cv,변동계수)

tail(pop_reg_cv)
```

## 변동계수 그래프를 그리자

```{r}
par(family = "AppleGothic")
barplot(pop_reg_cv$변동계수,
        names = pop_reg_cv$광역시도,
        cex.names = 0.5,
        xlab = "광역시도",
        ylab = "변동계수",
        main = "광역시도별 인구수 변동계수",
        ylim = c(0,max(pop_reg_cv$변동계수)+0.2),
        col = ifelse(pop_reg_cv$광역시도 == "서울특별시" |
                     pop_reg_cv$광역시도 == "세종특별자치시"
                     ,"red","blue")
        )
```
