-   수행능력 R \< Python \< Julia

-   IT는 무조건 유행이다. 유행 따라가지 않으면 도태된다.

# \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

# Machine Learning Model 저장하기

-   JSP를 이용해서 Machine Learning Model을 불러오는 것이다.

## RandomForest Model을 이용한 Species 예측

```{r}
library(randomForest)
```

```{r}
samp <- createDataPartition(iris$Species, p = 0.7 , list = F)
data.train <- iris[samp,]
data.test <- iris[-samp,]
```

```{r}
x <- subset(data.test ,select =  -Species)
y <- data.test$Species
```

```{r}
model.rf <- randomForest(Species ~ . , data.train , ntree = 100)
pred <- predict(model.rf , x)
```

```{r}
mean(pred == y) * 100
table(pred , y)
```

## model.rf 를 확인 후 전체 데이터 학습 시킨 후 저장하기

```{r}
model.rf <- randomForest(Species ~ . , data = iris , ntree = 100)
```

```{r}
# machine learning model 저장시키기
saveRDS(model.rf , "./Data/randomForest_iris.rds")
```

## 만든 AI 모델 불러와서 써먹을 수 있는지 확인하기

-   이 부분들이 R이 아니라 JSP에서 사용이 된다고 생각하면 된다.

```{r}
# rds가 어떠한 모델인지에 따라 불러와야 되는 패키지가 다르다.
library(randomForest)

# AI 모델 불러오기
rf <- readRDS("./Data/randomForest_iris.rds")
```

-   테스트 해보기

```{r}
predict(rf , list(Sepal.Length = 5.4,
                  Sepal.Width = 3.9,
                  Petal.Length = 1.7,
                  Petal.Width = 0.5))
```
