# MySQL 연결

```{r}
# R version 확인
version
```

-   연결을 위한 package 설치

```{r}
install.packages("rJava")
install.packages("RMySQL")
```

-   library 불러오기

```{r}
library(RMySQL)
```

-   DB 연결하기

```{r}
conn <- dbConnect(MySQL(),
                  dbname = "RSQL",
                  user = "root",
                  password = "tnstjd12",
                  host = "127.0.0.1"
                  )
```

-   테이블 목록

```{r}
dbListTables(conn)
```

-   컬럼 목록

```{r}
dbListFields(conn, "score")
```

# CRUD

-   select

```{r}
result <- dbGetQuery(conn, 'select count(*) as count from score')
result
```

-   insert

```{r}
dbSendQuery(conn, 'insert into score values (2,100,100,100)')
result <- dbGetQuery(conn, 'select * from score')
result
```

-   update

```{r}
dbSendQuery(conn, 'update score set korean = 90, english = 80, mathematics = 70 
                   where id = 2')
result <- dbGetQuery(conn, 'select * from score')
result
```

-   delete

```{r}
dbSendQuery(conn, 'delete from score where id = 2')
result <- dbGetQuery(conn, 'select * from score')
result
```

-   delete로 전부 지우기

```{r}
dbSendQuery(conn, 'delete from score')
result <- dbGetQuery(conn, 'select * from score')
result
```

# MySQL로 csv file 올리기

-   파일 불러오기

```{r}
data <- read.csv("./Data/score.csv", header = F)
colnames(data) <- c("id","korean","english","mathematics")
data
```

-   MySQL 에 csv file 올리기

    -   이거를 쳐줘야 연결이 된다.

        ``` sqlmysql
        show variables like 'local_infile';
        set global local_infile = 1;
        ```

```{r}
# overwrite를 쓸 시 계속 덮어쓰기를 한다. 
dbWriteTable(conn, "score" , data , overwrite = T , row.names = F )
result <- dbGetQuery(conn, 'select * from score')
result
```

-   data 추가하기

```{r}
data <- read.csv("./Data/score2.csv", header = F)
colnames(data) <- c("id","korean","english","mathematics")
data
```

```{r}
# append 를 쓸 시 추가로 들어간다.
dbWriteTable(conn, "score" , data , append = T , row.names = F )
result <- dbGetQuery(conn, 'select * from score')
result
```

# Disconnect 하기

```{r}
dbDisconnect(conn)
```
