# 생활인구 데이터 정제하기

## 2017년 \~ 2021년

```{r}
commer_pop_2021 <- read.csv("./Data/LivingPopulation/seoul_living_pop_2021.csv",fileEncoding = "euc-kr")

commer_pop_2020 <- read.csv("./Data/LivingPopulation/seoul_living_pop_2020.csv",fileEncoding = "euc-kr")

commer_pop_2019 <- read.csv("./Data/LivingPopulation/seoul_living_pop_2019.csv",fileEncoding = "euc-kr")

commer_pop_2018 <- read.csv("./Data/LivingPopulation/seoul_living_pop_2018.csv",fileEncoding = "euc-kr")

commer_pop_2017 <- read.csv("./Data/LivingPopulation/seoul_living_pop_2017.csv",fileEncoding = "euc-kr")

```

```{r}
# 2021
# 공통 컬럼 1,2,6
# 성별 8,9
# 연령대별 10 ~ 15
# 시간대별 16 ~ 21
# 요일별 22 ~ 28

# 2020 , 2019 , 2018 , 2017 
# 공통 컬럼 1,2,6
# 성별 9,10
# 연령대별 11 ~ 16
# 시간대별 17 ~ 22
# 요일별 23 ~ 28 월요일부터 토요일까지만
```

## 요일별

```{r}
commer_pop_daily_2021 <- commer_pop_2021[,c(1,2,6,22:28)]
commer_pop_daily_2020 <- commer_pop_2020[,c(1,2,6,23:28)]
commer_pop_daily_2019 <- commer_pop_2019[,c(1,2,6,23:28)]
commer_pop_daily_2018 <- commer_pop_2018[,c(1,2,6,23:28)]
commer_pop_daily_2017 <- commer_pop_2017[,c(1,2,6,23:28)]

```

### 2021년

```{r}
test_row <- t(commer_pop_daily_2021[1,4:10])
daily <- c("월요일","화요일","수요일","목요일","금요일","토요일","일요일")
test_data_frame <- data.frame(commer_pop_daily_2021[1,1:3],daily,test_row,row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")
```

```{r}
for (i in 2:nrow(commer_pop_daily_2021)) {
  test_row_2 <-t(commer_pop_daily_2021[i,4:10])
  test_data_frame_2 <- data.frame(commer_pop_daily_2021[i,1:3],daily,test_row_2,row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_daily_2021<-test_data_frame
```

### 2020년

```{r}
test_row <- t(commer_pop_daily_2020[1,4:9])
daily <- c("월요일","화요일","수요일","목요일","금요일","토요일")
test_data_frame <- data.frame(commer_pop_daily_2020[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")
```

```{r}
for (i in 2:nrow(commer_pop_daily_2020)) {
  test_row_2 <-t(commer_pop_daily_2020[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_daily_2020[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_daily_2020<-test_data_frame
```

### 2019년

```{r}
test_row <- t(commer_pop_daily_2019[1,4:9])
daily <- c("월요일","화요일","수요일","목요일","금요일","토요일")
test_data_frame <- data.frame(commer_pop_daily_2019[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

```

```{r}
for (i in 2:nrow(commer_pop_daily_2019)) {
  test_row_2 <-t(commer_pop_daily_2019[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_daily_2019[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_daily_2019<-test_data_frame
```

### 2018년

```{r}
test_row <- t(commer_pop_daily_2018[1,4:9])
daily <- c("월요일","화요일","수요일","목요일","금요일","토요일")
test_data_frame <- data.frame(commer_pop_daily_2018[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")
```

```{r}
for (i in 2:nrow(commer_pop_daily_2018)) {
  test_row_2 <-t(commer_pop_daily_2018[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_daily_2018[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_daily_2018<-test_data_frame
```

### 2017년

```{r}
test_row <- t(commer_pop_daily_2017[1,4:9])
daily <- c("월요일","화요일","수요일","목요일","금요일","토요일")
test_data_frame <- data.frame(commer_pop_daily_2017[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")
```

```{r}
for (i in 2:nrow(commer_pop_daily_2017)) {
  test_row_2 <-t(commer_pop_daily_2017[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_daily_2017[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_daily_2017<-test_data_frame
```

### 합치기

```{r}
commer_pop<-rbind(commer_pop_daily_2021,commer_pop_daily_2020,commer_pop_daily_2019,commer_pop_daily_2018,commer_pop_daily_2017)

write.csv(commer_pop,"./Data/commer_pop.csv",row.names = F)
```

## 시간대별

```{r}
commer_pop_time_2021 <- commer_pop_2021[,c(1,2,6,16:21)]
commer_pop_time_2020 <- commer_pop_2020[,c(1,2,6,17:22)]
commer_pop_time_2019 <- commer_pop_2019[,c(1,2,6,17:22)]
commer_pop_time_2018 <- commer_pop_2018[,c(1,2,6,17:22)]
commer_pop_time_2017 <- commer_pop_2017[,c(1,2,6,17:22)]
```

### 2021년

```{r}
test_row <- t(commer_pop_time_2021[1,4:9])
daily <- c("00시~06시","06시~11시","11시~14시","14시~17시","17시~21시","21시~24시")
test_data_frame <- data.frame(commer_pop_time_2021[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")
```

```{r}
for (i in 2:nrow(commer_pop_time_2021)) {
  test_row_2 <-t(commer_pop_time_2021[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_time_2021[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_time_2021<-test_data_frame
```

### 2020년

```{r}
test_row <- t(commer_pop_time_2020[1,4:9])
daily <- c("00시-06시","06시-11시","11시-14시","14시-17시","17시-21시","21시-24시")
test_data_frame <- data.frame(commer_pop_time_2020[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")


```

```{r}
for (i in 2:nrow(commer_pop_time_2020)) {
  test_row_2 <-t(commer_pop_time_2020[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_time_2020[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_time_2020<-test_data_frame
```

### 2019년

```{r}
test_row <- t(commer_pop_time_2019[1,4:9])
daily <- c("00시~06시","06시~11시","11시~14시","14시~17시","17시~21시","21시~24시")
test_data_frame <- data.frame(commer_pop_time_2019[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_time_2019)) {
  test_row_2 <-t(commer_pop_time_2019[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_time_2019[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_time_2019<-test_data_frame
```

### 2018년

```{r}
test_row <- t(commer_pop_time_2018[1,4:9])
daily <- c("00시~06시","06시~11시","11시~14시","14시~17시","17시~21시","21시~24시")
test_data_frame <- data.frame(commer_pop_time_2018[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_time_2018)) {
  test_row_2 <-t(commer_pop_time_2018[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_time_2018[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_time_2018<-test_data_frame
```

### 2017년

```{r}
test_row <- t(commer_pop_time_2017[1,4:9])
daily <- c("00시~06시","06시~11시","11시~14시","14시~17시","17시~21시","21시~24시")
test_data_frame <- data.frame(commer_pop_time_2017[1,1:3],daily,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_time_2017)) {
  test_row_2 <-t(commer_pop_time_2017[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_time_2017[i,1:3],daily,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_time_2017<-test_data_frame
```

### 합치기

```{r}
commer_pop_time <- rbind(commer_pop_time_2021,commer_pop_time_2020,commer_pop_time_2019,commer_pop_time_2018,commer_pop_time_2017,row.names = F)

rownames(commer_pop_time) <- c()
write.csv(commer_pop_time,"./Data/commer_pop_time.csv",row.names = F)
```

## 연령대별

```{r}
commer_pop_age_2021 <- commer_pop_2021[,c(1,2,6,10:15)]
commer_pop_age_2020 <- commer_pop_2020[,c(1,2,6,11:16)]
commer_pop_age_2019 <- commer_pop_2019[,c(1,2,6,11:16)]
commer_pop_age_2018 <- commer_pop_2018[,c(1,2,6,11:16)]
commer_pop_age_2017 <- commer_pop_2017[,c(1,2,6,11:16)]
```

### 2021년

```{r}
test_row <- t(commer_pop_age_2021[1,4:9])
age <- c(10,20,30,40,50,60)
test_data_frame <- data.frame(commer_pop_age_2021[1,1:3],age,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_age_2021)) {
  test_row_2 <-t(commer_pop_age_2021[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_age_2021[i,1:3],age,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_age_2021<-test_data_frame
```

### 2020년

```{r}
test_row <- t(commer_pop_age_2020[1,4:9])
age <- c(10,20,30,40,50,60)
test_data_frame <- data.frame(commer_pop_age_2020[1,1:3],age,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_age_2020)) {
  test_row_2 <-t(commer_pop_age_2020[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_age_2020[i,1:3],age,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_age_2020<-test_data_frame
```

### 2019년

```{r}
test_row <- t(commer_pop_age_2019[1,4:9])
age <- c(10,20,30,40,50,60)
test_data_frame <- data.frame(commer_pop_age_2019[1,1:3],age,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_age_2019)) {
  test_row_2 <-t(commer_pop_age_2019[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_age_2019[i,1:3],age,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_age_2019<-test_data_frame
```

### 2018년

```{r}
test_row <- t(commer_pop_age_2018[1,4:9])
age <- c(10,20,30,40,50,60)
test_data_frame <- data.frame(commer_pop_age_2018[1,1:3],age,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_age_2018)) {
  test_row_2 <-t(commer_pop_age_2018[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_age_2018[i,1:3],age,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_age_2018<-test_data_frame
```

### 2017년

```{r}
test_row <- t(commer_pop_age_2017[1,4:9])
age <- c(10,20,30,40,50,60)
test_data_frame <- data.frame(commer_pop_age_2017[1,1:3],age,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","요일","인구수")

for (i in 2:nrow(commer_pop_age_2017)) {
  test_row_2 <-t(commer_pop_age_2017[i,4:9])
  test_data_frame_2 <- data.frame(commer_pop_age_2017[i,1:3],age,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","요일","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_age_2017<-test_data_frame
```

### 합치기

```{r}
commer_pop_age <- rbind(commer_pop_age_2021,commer_pop_age_2020,commer_pop_age_2019,commer_pop_age_2018,commer_pop_age_2017,row.names = F)

rownames(commer_pop_age) <- c()
colnames(commer_pop_age) <- c("년도","분기","상권명","연령대별","인구수")
write.csv(commer_pop_age,"./Data/commer_pop_age.csv",row.names = F)
```

## 성별

```{r}
commer_pop_gen_2021 <- commer_pop_2021[,c(1,2,6,8,9)]
commer_pop_gen_2020 <- commer_pop_2020[,c(1,2,6,9,10)]
commer_pop_gen_2019 <- commer_pop_2019[,c(1,2,6,9,10)]
commer_pop_gen_2018 <- commer_pop_2018[,c(1,2,6,9,10)]
commer_pop_gen_2017 <- commer_pop_2017[,c(1,2,6,9,10)]
```

### 2021년

```{r}
test_row <- t(commer_pop_gen_2021[1,4:5])
gen <- c("남성","여성")
test_data_frame <- data.frame(commer_pop_gen_2021[1,1:3],gen,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","성별","인구수")

for (i in 2:nrow(commer_pop_gen_2021)) {
  test_row_2 <-t(commer_pop_gen_2021[i,4:5])
  test_data_frame_2 <- data.frame(commer_pop_gen_2021[i,1:3],gen,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","성별","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_gen_2021<-test_data_frame
```

### 2020년

```{r}
test_row <- t(commer_pop_gen_2020[1,4:5])
gen <- c("남성","여성")
test_data_frame <- data.frame(commer_pop_gen_2020[1,1:3],gen,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","성별","인구수")

for (i in 2:nrow(commer_pop_gen_2020)) {
  test_row_2 <-t(commer_pop_gen_2020[i,4:5])
  test_data_frame_2 <- data.frame(commer_pop_gen_2020[i,1:3],gen,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","성별","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_gen_2020<-test_data_frame
```

### 2019년

```{r}
test_row <- t(commer_pop_gen_2019[1,4:5])
gen <- c("남성","여성")
test_data_frame <- data.frame(commer_pop_gen_2019[1,1:3],gen,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","성별","인구수")

for (i in 2:nrow(commer_pop_gen_2019)) {
  test_row_2 <-t(commer_pop_gen_2019[i,4:5])
  test_data_frame_2 <- data.frame(commer_pop_gen_2019[i,1:3],gen,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","성별","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_gen_2019<-test_data_frame
```

### 2018년

```{r}
test_row <- t(commer_pop_gen_2018[1,4:5])
gen <- c("남성","여성")
test_data_frame <- data.frame(commer_pop_gen_2018[1,1:3],gen,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","성별","인구수")

for (i in 2:nrow(commer_pop_gen_2018)) {
  test_row_2 <-t(commer_pop_gen_2018[i,4:5])
  test_data_frame_2 <- data.frame(commer_pop_gen_2018[i,1:3],gen,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","성별","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_gen_2018<-test_data_frame
```

### 2017년

```{r}
test_row <- t(commer_pop_gen_2017[1,4:5])
gen <- c("남성","여성")
test_data_frame <- data.frame(commer_pop_gen_2017[1,1:3],gen,test_row, row.names = NULL)
colnames(test_data_frame)<-c("년도","분기","상권명","성별","인구수")

for (i in 2:nrow(commer_pop_gen_2017)) {
  test_row_2 <-t(commer_pop_gen_2017[i,4:5])
  test_data_frame_2 <- data.frame(commer_pop_gen_2017[i,1:3],gen,test_row_2, row.names = NULL)
  colnames(test_data_frame_2)<-c("년도","분기","상권명","성별","인구수")
  test_data_frame <- rbind(test_data_frame, test_data_frame_2)
}
rownames(test_data_frame) <- c()

commer_pop_gen_2017<-test_data_frame
```

### 합치기

```{r}
commer_pop_gen <- rbind(commer_pop_gen_2021,commer_pop_gen_2020,commer_pop_gen_2019,commer_pop_gen_2018,commer_pop_gen_2017,row.names = F)

rownames(commer_pop_gen) <- c()
write.csv(commer_pop_gen,"./Data/commer_pop_gen.csv",row.names = F)
```
